[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

[client]
toolbarMode = "auto"
showErrorDetails = true

[logger]
level = "info"

[global]
developmentMode = false
useNode = false

[packages]
usePackageManager = "pip"

[ui]
hideTopBar = false

[mapbox]
token = ""

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false 