# .streamlit/secrets_example.toml
# Copy this file to .streamlit/secrets.toml (local development)
# Or add these values to the Streamlit Cloud dashboard secrets

[api_keys]
# Core APIs
openai = "your_openai_key"
perplexity = "your_perplexity_key"
crawl4ai = "your_crawl4ai_key"
metaculus = "your_metaculus_token"

# Financial Data APIs
fred = "your_fred_key"
iex_cloud = "your_iex_cloud_key"
alpha_vantage = "your_alphavantage_key"
quandl = "your_quandl_key"

# Additional APIs
world_bank = "your_world_bank_key"
bloomberg = "your_bloomberg_key" 